---
version: '3.8'
services:
  app:
    build:
      context: "."
      dockerfile: Dockerfile.release
    ports:
    - 3000:3000
    volumes:
    - ".:/app"
    depends_on:
    - db
    - redis
  db:
    image: mongo:latest
    ports:
    - 27017:27017
  redis:
    image: redis:latest
    ports:
    - '6379'
